// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// streamxform
NumericMatrix streamxform(NumericMatrix points, CharacterVector reglist, double inversionTolerance = 1e-8);
RcppExport SEXP cmtkr_streamxform(SEXP pointsSEXP, SEXP reglistSEXP, SEXP inversionToleranceSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type reglist(reglistSEXP );
        Rcpp::traits::input_parameter< double >::type inversionTolerance(inversionToleranceSEXP );
        NumericMatrix __result = streamxform(points, reglist, inversionTolerance);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
