# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' streamxform a set of points
#' @param points an Nx3 set of 3D points
#' @export
streamxform <- function(points, reglist) {
    .Call('cmtkr_streamxform', PACKAGE = 'cmtkr', points, reglist)
}

